### PR TITLE
Add cross-platform compatibility

### PR DESCRIPTION
**Pull request by rivy**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? This module is meant for Linux.

**Comment by rivy** [comment]
Some otherwise cross-platform scripts use the XDG spec. And there's no reason that the XDG environment variables need to be restricted to only *nix.

This is, IMO, a minor step to make this more cross platform compatible, without sacrificing any *nix compatibility.

Otherwise, you could be explicit in your *package.json*, adding `os: [ "linux" ]` to restrict use and formally disallow other platforms (causing installation errors).

**Comment by sindresorhus** [comment]
I'm gonna pass on this. I don't want to encourage incorrect usage of it. XDG is meant for Linux. I've clarified that in the readme now.

---

> Otherwise, you could be explicit in your package.json, adding os: [ "linux" ] to restrict use and formally disallow other platforms (causing installation errors).

That is an anti-pattern, as it means project cannot use this package, even if they put it in a conditional, as it will fail to even install on other systems.

**Comment by sindresorhus** [comment]
If a tool you're using is using this package for cross-platform scripts, you should encourage them to use https://github.com/sindresorhus/env-paths instead ;)

**Comment by rivy** [comment]
Thanks for the consideration.
I'd already made some mods to `env-paths` as well that support portable XDG.
And, since I need cross-platform compatibility, I'll just fork the modules instead.

- [`xdg-portable`](https://www.npmjs.com/package/xdg-portable) and [`xdg-app-paths`](https://www.npmjs.com/package/xdg-app-paths)

**Pull request closed without merging**
